Repository DeKal/illuminati, pull requests merged in 2020-02, with the labels that each got.

#82 [#81] Fix Hot-swaping with devtools, continuous auto-restart app
  README.md
  build.gradle
Labels: bug

#88 [Improve] Adding docs
  README.md
  docs/cd.md
  docs/ci.md
  docs/dev.md
  docs/install.md
  docs/mongo_guide.md
  docs/mongo_import_export.md
  docs/process.md
  docs/release.md
  docs/test.md
Labels: documentation

#80 [#60] Update get post to return similar Response
  src/main/java/com/dawn/jat/illuminati/core/response/SuccessResponse.java
  src/main/java/com/dawn/jat/illuminati/post/advice/PostExceptionAdvice.java
  src/main/java/com/dawn/jat/illuminati/post/controller/PostController.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepository.java
  src/test/java/com/dawn/jat/illuminati/post/advice/PostExceptionAdviceTest.java
  src/test/java/com/dawn/jat/illuminati/post/controller/PostControllerTest.java
Labels: enhancement
