Repository DeKal/illuminati, pull requests merged in 2020-06, with the labels that each got.

#211 [#210] Disable CSRF
  src/main/java/com/dawn/jat/illuminati/WebSecurityConfig.java
  src/main/resources/application-prod.properties
  src/main/resources/application-staging.properties
  src/main/resources/application.properties
Labels: bug, enhancement

#215 [Update] Remove code quality from Scrutinize and try sonar cloud
  .scrutinizer.yml
Labels: enhancement

#214 [Refactor] Refactor login module
  src/main/java/com/dawn/jat/illuminati/WebSecurityConfig.java
  src/main/java/com/dawn/jat/illuminati/login/authority/AdminAuthority.java
  src/main/java/com/dawn/jat/illuminati/login/authority/NormalAuthority.java
  src/main/java/com/dawn/jat/illuminati/login/authority/UserAuthority.java
  src/main/java/com/dawn/jat/illuminati/login/provider/UserAuthenticationProvider.java
  src/main/resources/static/login/vendor/animsition/css/animsition.css
  src/main/resources/static/login/vendor/animsition/js/animsition.js
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap-grid.css
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap-grid.css.map
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap-grid.min.css.map
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap-reboot.css
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap-reboot.css.map
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap.css
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap.css.map
  src/main/resources/static/login/vendor/bootstrap/css/bootstrap.min.css.map
  src/main/resources/static/login/vendor/bootstrap/js/bootstrap.js
  src/main/resources/static/login/vendor/bootstrap/js/popper.js
  src/main/resources/static/login/vendor/css-hamburgers/hamburgers.css
  src/main/resources/templates/login/index.html
  src/test/java/com/dawn/jat/illuminati/login/provider/UserAuthenticationProviderTest.java
Labels: enhancement

#216 [Sonar] Fix potential HTML bugs
  src/main/resources/static/login/css/main.css
  src/main/resources/templates/cms/index.html
Labels: enhancement

#218 [#217] Adding swagger
  README.md
  build.gradle
  docs/HELP.md
  docs/swagger.md
  src/main/java/com/dawn/jat/illuminati/Application.java
  src/main/java/com/dawn/jat/illuminati/core/config/AppConfig.java
  src/main/java/com/dawn/jat/illuminati/core/config/ServletConfig.java
  src/main/java/com/dawn/jat/illuminati/core/config/WebSecurityConfig.java
  src/main/java/com/dawn/jat/illuminati/docs/config/SpringFoxConfig.java
  src/main/java/com/dawn/jat/illuminati/docs/controller/DocController.java
  src/main/java/com/dawn/jat/illuminati/docs/entity/ErrorPayload.java
  src/main/java/com/dawn/jat/illuminati/docs/entity/GetPostResponse.java
  src/main/java/com/dawn/jat/illuminati/docs/entity/InternalServerResponse.java
  src/main/java/com/dawn/jat/illuminati/docs/entity/PostSummariesResponse.java
  src/main/java/com/dawn/jat/illuminati/post/controller/PostController.java
Labels: documentation, enhancement

#207 Refactor code
  build.gradle
  src/main/java/com/dawn/jat/illuminati/core/config/AppConfig.java
  src/main/java/com/dawn/jat/illuminati/core/mapper/Converter.java
  src/main/java/com/dawn/jat/illuminati/core/response/ErrorResponse.java
  src/main/java/com/dawn/jat/illuminati/docs/config/SpringFoxConfig.java
  src/main/java/com/dawn/jat/illuminati/docs/entity/PostSummariesResponse.java
  src/main/java/com/dawn/jat/illuminati/login/entity/User.java
  src/main/java/com/dawn/jat/illuminati/login/provider/UserAuthenticationProvider.java
  src/main/java/com/dawn/jat/illuminati/login/repository/LoginRepository.java
  src/main/java/com/dawn/jat/illuminati/login/service/LoginService.java
  src/main/java/com/dawn/jat/illuminati/post/controller/PostController.java
  src/main/java/com/dawn/jat/illuminati/post/dto/PostDto.java
  src/main/java/com/dawn/jat/illuminati/post/entity/PostEntity.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepository.java
  src/main/java/com/dawn/jat/illuminati/post/service/PostService.java
  src/test/java/com/dawn/jat/illuminati/core/mapper/ConverterTest.java
  src/test/java/com/dawn/jat/illuminati/post/controller/PostControllerTest.java
  src/test/java/com/dawn/jat/illuminati/post/service/PostServiceTest.java
Labels: enhancement

#239 [Improve] Improve error boundary
  cms/src/core/utils/__test__/misc.spec.js
  cms/src/core/utils/misc.js
  cms/src/error/components/Error.js
  cms/src/error/components/base/Layout.js
  cms/src/error/components/base/__tests__/__snapshots__/Layout.spec.js.snap
Labels: enhancement

#238 [#213] Upgrade to Java 11
  .circleci/config.yml
  build.gradle
  docs/ci.md
  system.properties
Labels: dependencies, enhancement
