Repository DeKal/illuminati, pull requests merged in 2020-03, with the labels that each got.

#100 [#99] Adding layout for cms app
  cms/package.json
  cms/public/index.html
  cms/src/app/App.css
  cms/src/app/App.js
  cms/src/app/App.spec.js
  cms/src/app/__snapshots__/App.spec.js.snap
  cms/src/core/components/App.js
  cms/src/core/components/Drawer.js
  cms/src/core/components/NavBar.js
  cms/src/core/components/PageSwitch.js
  cms/src/core/components/__tests__/App.spec.js
  cms/src/core/components/__tests__/Drawer.spec.js
  cms/src/core/components/__tests__/NavBar.spec.js
  cms/src/core/components/__tests__/PageSwitch.spec.js
  cms/src/core/components/__tests__/__snapshots__/App.spec.js.snap
  cms/src/core/components/__tests__/__snapshots__/Drawer.spec.js.snap
  cms/src/core/components/__tests__/__snapshots__/NavBar.spec.js.snap
  cms/src/core/components/__tests__/__snapshots__/PageSwitch.spec.js.snap
  cms/src/core/components/page/Container.js
  cms/src/core/components/page/__tests__/Container.spec.js
  cms/src/core/components/page/__tests__/__snapshots__/Container.spec.js.snap
  cms/src/core/const/actionType.js
  cms/src/core/containers/App.js
  cms/src/core/containers/Drawer.js
  cms/src/core/containers/NavBar.js
  cms/src/core/init/initStore.js
  cms/src/core/state/app/action.js
  cms/src/core/state/app/action.spec.js
  cms/src/core/state/app/reducer.spec.js
  cms/src/core/state/app/reducers.js
  cms/src/core/state/drawer/__tests__/__snapshots__/action.spec.js.snap
  cms/src/core/state/drawer/__tests__/action.spec.js
  cms/src/core/state/drawer/__tests__/reducers.spec.js
  cms/src/core/state/drawer/actions.js
  cms/src/core/state/drawer/reducers.js
  cms/src/core/state/rootReducer.js
  cms/src/core/theme/ThemeWrapper.js
  cms/src/core/theme/theme.js
  cms/src/dashboard/components/Dashboard.js
  cms/src/dashboard/components/__tests__/Dashboard.spec.js
  cms/src/dashboard/components/__tests__/__snapshots__/Dashboard.spec.js.snap
  cms/src/index.css
  cms/src/index.js
  cms/src/user/components/User.js
  cms/src/user/components/__tests__/User.spec.js
  cms/src/user/components/__tests__/__snapshots__/User.spec.js.snap
  cms/yarn.lock
Labels: enhancement

#103 [Hot-fix] Fix reducer broken due to remove default case
  cms/src/core/state/drawer/__tests__/reducers.spec.js
  cms/src/core/state/drawer/reducers.js
Labels: bug

#98 Repository extends use MongoTemplate
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepository.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepositoryTemplate.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepositoryTemplateImpl.java
  src/main/java/com/dawn/jat/illuminati/post/service/PostService.java
  src/test/java/com/dawn/jat/illuminati/post/service/PostServiceTest.java
Labels: enhancement, java

#104 [#102] Fix route cms/* does not lead to cms
  src/main/java/com/dawn/jat/illuminati/cms/controller/CmsController.java
Labels: bug

#108 [#101] Update README
  README.md
  cms/README.md
Labels: documentation

#110 [#109] Improve Drawer
  cms/src/core/components/Drawer.js
  cms/src/core/components/NavBar.js
  cms/src/core/components/PageSwitch.js
  cms/src/core/components/__tests__/Drawer.spec.js
  cms/src/core/components/__tests__/NavBar.spec.js
  cms/src/core/components/__tests__/__snapshots__/App.spec.js.snap
  cms/src/core/components/__tests__/__snapshots__/Drawer.spec.js.snap
  cms/src/core/components/__tests__/__snapshots__/PageSwitch.spec.js.snap
  cms/src/core/const/pages.js
  cms/src/core/containers/Drawer.js
  cms/src/core/theme/theme.js
Labels: enhancement

#114 [Hot-enhance] Enhance Scrutinizer config
  .scrutinizer.yml
Labels: enhancement

#115 [#111] Drawer open state will be persisted
  cms/package.json
  cms/src/core/init/initStore.js
  cms/src/core/state/configureStore.js
  cms/src/index.js
  cms/yarn.lock
Labels: enhancement

#116 [#107] Adding Dashboard along with UI fix
  cms/src/core/components/Drawer.js
  cms/src/core/components/__tests__/Drawer.spec.js
  cms/src/core/components/page/Container.js
  cms/src/core/const/pages.js
  cms/src/core/containers/App.js
  cms/src/core/containers/Drawer.js
  cms/src/core/containers/NavBar.js
  cms/src/core/theme/theme.js
  cms/src/core/utils/__test__/__snapshots__/test-helper.spec.js.snap
  cms/src/core/utils/__test__/misc.spec.js
  cms/src/core/utils/__test__/test-helper.spec.js
  cms/src/core/utils/misc.js
  cms/src/core/utils/test-helper.js
  cms/src/dashboard/components/Dashboard.js
  cms/src/dashboard/components/GetStarted.js
  cms/src/dashboard/components/GetStarted/Button.js
  cms/src/dashboard/components/GetStarted/Container.js
  cms/src/dashboard/components/GetStarted/Item.js
  cms/src/dashboard/components/GetStarted/ItemTitle.js
  cms/src/dashboard/components/GetStarted/SubTitle.js
  cms/src/dashboard/components/GetStarted/Title.js
  cms/src/dashboard/components/GetStarted/__tests__/Button.spec.js
  cms/src/dashboard/components/GetStarted/__tests__/Container.spec.js
  cms/src/dashboard/components/GetStarted/__tests__/ItemTitle.spec.js
  cms/src/dashboard/components/GetStarted/__tests__/SubTitle.spec.js
  cms/src/dashboard/components/GetStarted/__tests__/Title.spec.js
  cms/src/dashboard/components/GetStarted/__tests__/__snapshots__/Button.spec.js.snap
  cms/src/dashboard/components/GetStarted/__tests__/__snapshots__/Container.spec.js.snap
  cms/src/dashboard/components/GetStarted/__tests__/__snapshots__/ItemTitle.spec.js.snap
  cms/src/dashboard/components/GetStarted/__tests__/__snapshots__/SubTitle.spec.js.snap
  cms/src/dashboard/components/GetStarted/__tests__/__snapshots__/Title.spec.js.snap
  cms/src/dashboard/components/__tests__/GetStarted.spec.js
  cms/src/dashboard/components/__tests__/__snapshots__/Dashboard.spec.js.snap
  cms/src/dashboard/components/__tests__/__snapshots__/GetStarted.spec.js.snap
Labels: enhancement

#131 [#130]: Add loading component when requesting server
  cms/src/core/components/Loading.js
  cms/src/core/components/__tests__/Loading.spec.js
  cms/src/core/components/__tests__/__snapshots__/Loading.spec.js.snap
  cms/src/core/components/page/Container.js
  cms/src/core/theme/theme.js
  cms/src/posts/components/Posts.js
  cms/src/posts/components/__tests__/Posts.spec.js
  cms/src/posts/components/__tests__/__snapshots__/Posts.spec.js.snap
Labels: enhancement

#133 [Hot-fix] Fix cms/ using ** instead of * and remove route / to cms
  src/main/java/com/dawn/jat/illuminati/cms/controller/CmsController.java
Labels: enhancement

#135 Add save post
  build.gradle
  docs/dev.md
  scripts/hot-reload-server.sh
  scripts/hot-reload-with-cms.sh
  scripts/run.sh
  src/main/java/com/dawn/jat/illuminati/cms/controller/CmsController.java
  src/main/java/com/dawn/jat/illuminati/core/convert/Converter.java
  src/main/java/com/dawn/jat/illuminati/post/advice/PostExceptionAdvice.java
  src/main/java/com/dawn/jat/illuminati/post/controller/PostController.java
  src/main/java/com/dawn/jat/illuminati/post/dto/PostDto.java
  src/main/java/com/dawn/jat/illuminati/post/entity/PostEntity.java
  src/main/java/com/dawn/jat/illuminati/post/exception/PostCannotBeSavedException.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepository.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepositoryTemplate.java
  src/main/java/com/dawn/jat/illuminati/post/repository/PostRepositoryTemplateImpl.java
  src/main/java/com/dawn/jat/illuminati/post/service/PostService.java
  src/main/resources/application-prod.properties
  src/main/resources/application-staging.properties
  src/main/resources/application.properties
  src/test/java/com/dawn/jat/illuminati/core/convert/ConverterTest.java
  src/test/java/com/dawn/jat/illuminati/core/response/SuccessResponseTest.java
  src/test/java/com/dawn/jat/illuminati/post/advice/PostExceptionAdviceTest.java
  src/test/java/com/dawn/jat/illuminati/post/controller/PostControllerTest.java
  src/test/java/com/dawn/jat/illuminati/post/service/PostServiceTest.java
Labels: enhancement
